#! /bin/sh

# Copyright (C) 2022  HimbeerserverDE
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

KEYMAP=$(cat ~/.xkeymap)
if [ -n "${KEYMAP}" ]; then
	setxkbmap -layout ${KEYMAP}
fi

pgrep -x sxhkd > /dev/null || sxhkd &

xss-lock --transfer-sleep-lock -- i3lock-fancy-rapid 1 10 &

killall -qw pipewire; pipewire &
while [ -z "$(pgrep -x pipewire)" ]; do false; done
killall -qw pipewire-pulse; pipewire-pulse &
while [ -z "$(pgrep -x pipewire-pulse)" ]; do false; done
killall -qw wireplumber; wireplumber &

feh --no-fehbg --bg-fill ~/.config/bspwm/wallpaper

# load the normal mode polybar
ln -snf ${HOME}/.config/polybar.d/normal ${HOME}/.config/polybar 

killall -qw picom; picom -b
killall -qw dunst; dunst &
killall -qw polybar; ~/.config/polybar/launch.sh &
killall -qw init_monitor.sh; ~/.config/bspwm/init_monitor.sh &

bspc monitor 'eDP1' -n 1 -d 1 2 3 4 5 6 7 8 9

bspc config border_width		0
bspc config window_gap			10

bspc config split_ratio			0.52
bspc config borderless_monocle	true
bspc config gapless_monocle		true
